version: "2"
services:
  gogs:
    container_name: gogs
    image: gogs/gogs
    ports:
      - 3000:3000
    volumes:
      - ./data/gogs/data:/data
    environment:
      - TZ=Asia/Shanghai
    restart: always

  drone-server:
    image: drone/drone:1.0.0-rc.6
    container_name: drone-server
    ports:
      - 8000:80
    volumes:
      - /var/run/docker/docker.sock:/var/run/docker/docker.sock
      - ./data/drone/:/var/lib/drone
    environment:
      - DRONE_OPEN=true
      - DRONE_SERVER_HOST=drone-server:8000
      - DRONE_DEBUG=true
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_GOGS=true
      - DRONE_GOGS_SKIP_VERIFY=false
      - DRONE_GOGS_SERVER=http://127.0.0.1:3000
      - DRONE_PROVIDER=gogs
      - DRONE_SERVER_PROTO=http
      - DRONE_RPC_SECRET=7b4eb5caee376cf81a2fcf7181e66175
      - DRONE_USER_CREATE=username:alic,admin:true
      - DRONE_DATABASE_DATASOURCE=/var/lib/drone/drone.sqlite
      - DRONE_DATABASE_DRIVER=sqlite3
      - TZ=Asia/Shanghai
    restart: always

  drone-agent:
    image: drone/agent:1.0.0-rc.6
    container_name: drone-agent
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker/docker.sock:/var/run/docker/docker.sock
    environment:
      - DRONE_RPC_SERVER=127.0.0.1:9000
      - DRONE_RPC_SECRET=7b4eb5caee376cf81a2fcf7181e66175
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_DEBUG=true
      - TZ=Asia/Shanghai
    restart: always
